/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedScanWebsiteRouteImport } from './routes/_authenticated/scan.website'
import { Route as AuthenticatedScanShoppingRouteImport } from './routes/_authenticated/scan.shopping'
import { Route as AuthenticatedScanQrRouteImport } from './routes/_authenticated/scan.qr'
import { Route as AuthenticatedScanPaymentRouteImport } from './routes/_authenticated/scan.payment'
import { Route as AuthenticatedScanPasswordRouteImport } from './routes/_authenticated/scan.password'
import { Route as AuthenticatedScanEmailRouteImport } from './routes/_authenticated/scan.email'
import { Route as AuthenticatedScanDocumentRouteImport } from './routes/_authenticated/scan.document'
import { Route as AuthenticatedScanDeepfakeRouteImport } from './routes/_authenticated/scan.deepfake'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanWebsiteRoute =
  AuthenticatedScanWebsiteRouteImport.update({
    id: '/scan/website',
    path: '/scan/website',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanShoppingRoute =
  AuthenticatedScanShoppingRouteImport.update({
    id: '/scan/shopping',
    path: '/scan/shopping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanQrRoute = AuthenticatedScanQrRouteImport.update({
  id: '/scan/qr',
  path: '/scan/qr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanPaymentRoute =
  AuthenticatedScanPaymentRouteImport.update({
    id: '/scan/payment',
    path: '/scan/payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanPasswordRoute =
  AuthenticatedScanPasswordRouteImport.update({
    id: '/scan/password',
    path: '/scan/password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanEmailRoute = AuthenticatedScanEmailRouteImport.update({
  id: '/scan/email',
  path: '/scan/email',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanDocumentRoute =
  AuthenticatedScanDocumentRouteImport.update({
    id: '/scan/document',
    path: '/scan/document',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScanDeepfakeRoute =
  AuthenticatedScanDeepfakeRouteImport.update({
    id: '/scan/deepfake',
    path: '/scan/deepfake',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/performance': typeof PerformanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/scan/deepfake': typeof AuthenticatedScanDeepfakeRoute
  '/scan/document': typeof AuthenticatedScanDocumentRoute
  '/scan/email': typeof AuthenticatedScanEmailRoute
  '/scan/password': typeof AuthenticatedScanPasswordRoute
  '/scan/payment': typeof AuthenticatedScanPaymentRoute
  '/scan/qr': typeof AuthenticatedScanQrRoute
  '/scan/shopping': typeof AuthenticatedScanShoppingRoute
  '/scan/website': typeof AuthenticatedScanWebsiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/performance': typeof PerformanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/scan/deepfake': typeof AuthenticatedScanDeepfakeRoute
  '/scan/document': typeof AuthenticatedScanDocumentRoute
  '/scan/email': typeof AuthenticatedScanEmailRoute
  '/scan/password': typeof AuthenticatedScanPasswordRoute
  '/scan/payment': typeof AuthenticatedScanPaymentRoute
  '/scan/qr': typeof AuthenticatedScanQrRoute
  '/scan/shopping': typeof AuthenticatedScanShoppingRoute
  '/scan/website': typeof AuthenticatedScanWebsiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/performance': typeof PerformanceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/scan/deepfake': typeof AuthenticatedScanDeepfakeRoute
  '/_authenticated/scan/document': typeof AuthenticatedScanDocumentRoute
  '/_authenticated/scan/email': typeof AuthenticatedScanEmailRoute
  '/_authenticated/scan/password': typeof AuthenticatedScanPasswordRoute
  '/_authenticated/scan/payment': typeof AuthenticatedScanPaymentRoute
  '/_authenticated/scan/qr': typeof AuthenticatedScanQrRoute
  '/_authenticated/scan/shopping': typeof AuthenticatedScanShoppingRoute
  '/_authenticated/scan/website': typeof AuthenticatedScanWebsiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/performance'
    | '/sitemap.xml'
    | '/admin'
    | '/assistant'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/api/chat'
    | '/scan/deepfake'
    | '/scan/document'
    | '/scan/email'
    | '/scan/password'
    | '/scan/payment'
    | '/scan/qr'
    | '/scan/shopping'
    | '/scan/website'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/performance'
    | '/sitemap.xml'
    | '/admin'
    | '/assistant'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/api/chat'
    | '/scan/deepfake'
    | '/scan/document'
    | '/scan/email'
    | '/scan/password'
    | '/scan/payment'
    | '/scan/qr'
    | '/scan/shopping'
    | '/scan/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/performance'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/api/chat'
    | '/_authenticated/scan/deepfake'
    | '/_authenticated/scan/document'
    | '/_authenticated/scan/email'
    | '/_authenticated/scan/password'
    | '/_authenticated/scan/payment'
    | '/_authenticated/scan/qr'
    | '/_authenticated/scan/shopping'
    | '/_authenticated/scan/website'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PerformanceRoute: typeof PerformanceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/website': {
      id: '/_authenticated/scan/website'
      path: '/scan/website'
      fullPath: '/scan/website'
      preLoaderRoute: typeof AuthenticatedScanWebsiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/shopping': {
      id: '/_authenticated/scan/shopping'
      path: '/scan/shopping'
      fullPath: '/scan/shopping'
      preLoaderRoute: typeof AuthenticatedScanShoppingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/qr': {
      id: '/_authenticated/scan/qr'
      path: '/scan/qr'
      fullPath: '/scan/qr'
      preLoaderRoute: typeof AuthenticatedScanQrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/payment': {
      id: '/_authenticated/scan/payment'
      path: '/scan/payment'
      fullPath: '/scan/payment'
      preLoaderRoute: typeof AuthenticatedScanPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/password': {
      id: '/_authenticated/scan/password'
      path: '/scan/password'
      fullPath: '/scan/password'
      preLoaderRoute: typeof AuthenticatedScanPasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/email': {
      id: '/_authenticated/scan/email'
      path: '/scan/email'
      fullPath: '/scan/email'
      preLoaderRoute: typeof AuthenticatedScanEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/document': {
      id: '/_authenticated/scan/document'
      path: '/scan/document'
      fullPath: '/scan/document'
      preLoaderRoute: typeof AuthenticatedScanDocumentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/deepfake': {
      id: '/_authenticated/scan/deepfake'
      path: '/scan/deepfake'
      fullPath: '/scan/deepfake'
      preLoaderRoute: typeof AuthenticatedScanDeepfakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanDeepfakeRoute: typeof AuthenticatedScanDeepfakeRoute
  AuthenticatedScanDocumentRoute: typeof AuthenticatedScanDocumentRoute
  AuthenticatedScanEmailRoute: typeof AuthenticatedScanEmailRoute
  AuthenticatedScanPasswordRoute: typeof AuthenticatedScanPasswordRoute
  AuthenticatedScanPaymentRoute: typeof AuthenticatedScanPaymentRoute
  AuthenticatedScanQrRoute: typeof AuthenticatedScanQrRoute
  AuthenticatedScanShoppingRoute: typeof AuthenticatedScanShoppingRoute
  AuthenticatedScanWebsiteRoute: typeof AuthenticatedScanWebsiteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanDeepfakeRoute: AuthenticatedScanDeepfakeRoute,
  AuthenticatedScanDocumentRoute: AuthenticatedScanDocumentRoute,
  AuthenticatedScanEmailRoute: AuthenticatedScanEmailRoute,
  AuthenticatedScanPasswordRoute: AuthenticatedScanPasswordRoute,
  AuthenticatedScanPaymentRoute: AuthenticatedScanPaymentRoute,
  AuthenticatedScanQrRoute: AuthenticatedScanQrRoute,
  AuthenticatedScanShoppingRoute: AuthenticatedScanShoppingRoute,
  AuthenticatedScanWebsiteRoute: AuthenticatedScanWebsiteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PerformanceRoute: PerformanceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
